### ISSUE TITLE
Sintesis Webinar

### ISSUE THREAD

**Issue by Joel343** [SistemasTecTlaxiaco/sintesis-Joel343#2]
[Sintesis.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-Joel343/files/7146446/Sintesis.pdf)

**Comment by MarcosJonathan17** [comment]
Destaca la información  mas importante y precisa, resume de manera consistente el video de la "web binar", relaciona las ideas entre sí y cumple con los criterios de diseños planteados.

calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
